### ISSUE TITLE
OSX: sed: illegal option -- r 

### ISSUE THREAD

**Issue by arnim** [culturegraph/metafacture-runner#4]
./flux.sh 
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]

**Comment by redskate** [comment]
Thank you arnim - I USE macs and this was a nice hint
metafacture seems to have been developed for windows
