### ISSUE TITLE
$METAFACTURE_HOME/${project.build.finalName}.jar

### ISSUE THREAD

**Issue by redskate** [culturegraph/metafacture-runner#6]
Dear Culturegraph Team

I downloaded metafacture-runner on a mac osx and I wanted to run an example. After having corrected the "sed -R" in flux.sh I started with

./src/main/scripts/flux.sh ./src/main/resources/assembly-resources/examples/gnd/json/tp2json.flux 

The result was:

./src/main/scripts/flux.sh: line 51: $METAFACTURE_HOME/${project.build.finalName}.jar: bad substitution
Error: Could not find or load main class 

It seems that there is a var $METAFACTURE_HOME which should point to (what) ?

Thank you in advance for explaining where to find what $METAFACTURE_HOME should point at.

Regards

**Comment by cboehme** [comment]
Hi,

it looks like you are trying to run the scripts directly from the sources in the Maven project. This does not work as the scripts contain placeholders (e.g. ${project.build.finalName}) which are replaced during the Maven build process to create a working shell script.

If you want to build your own distribution package, you need to run `mvn clean package` in the base directory of the Maven project. Afterwards, you'll find a tar.gz file in the target directory which you can extract to have a working Metafacture runner distribution. Alternatively, you can download a prebuilt distribution package from https://github.com/culturegraph/metafacture-runner/releases.

If you have any problems running the scripts on mac, please let me know. I am happy to fix such problems, but as I do not have a mac, I cannot test whether the scripts are working on mac (I develop on Windows and Linux).

Best,
Christoph

**Comment by redskate** [comment]
Hi Christoph thank you for your response

I did what you suggest, I issued a command "mvn clean package" insider the git cloned metafacture-runner dir.

The result was:
Error: Could not find or load main class org.codehaus.plexus.classworlds.launcher.Launcher

I would like 1) to run metafacture with a flux example, then 2) to have a distribution copy to (maybe) add some connector from some source type. I installed the IDE on eclipse but I cannot figure out what to do with it, I guess I should create an own Java project, bind metafacture-core and do some transformation. Is there a Java Project Example to do that? (I know it is another issue)

Thank you in advance
Best
Fabio

**Comment by redskate** [comment]
My maven is not running well ... I'll make a check...

**Comment by redskate** [comment]
Hi Christoph

I repaired my maven, ran your command and got the jars inside the target directory.
Then I set
export METAFACTURE_HOME='/Users/fabio/Documents/workspace/metafacture-runner/target/metafacture-runner-3.0.1-SNAPSHOT.jar'

and ran 

./flux.sh ./src/main/resources/assembly-resources/examples/gnd/json/tp2json.flux

The result:

"Error: Could not find or load main class"

What did I do wrong?

Best
Fabio

**Comment by cboehme** [comment]
Hi Fabio,

it looks like you are trying to run flux directly from the _target_ directory. This won't work. You need to unzip the _metafacture-runner-3.1.3-SNAPSHOT-dist.tar.gz_ and run the flux.sh script contained in the extracted folder. 

By following the instructions below you should be able to run the metafacture example:
```sh
git clone https://github.com/culturegraph/metafacture-runner.git
cd metafacture-runner
# Fix sed -R issue in src/main/scripts/flux.sh
mvn clean package
cd target
tar xzf metafacture-runner-3.1.3-SNAPSHOT-dist.tar.gz
cd metafacture-runner-3.1.3-SNAPSHOT
./flux.sh example/gnd/json/tp2json.flux
```

btw: you do not need to set the `METAFACTURE_HOME` variable. The variable is set automatically by `flux.sh` based on the location of the script.

Regarding your second question: The metafacture-runner package is only needed for using metafacture as a command-line application. For java development, you only need to add the metafacture-core as dependency. You do not need the metafacture ide for working with metafacture in java. The ide was built with the intention to simplify writing flux and metamorph scripts.

I have created two maven archetypes which can be used as a starting point for developing an application using metafacture or a metafacture plugin. They have not yet been released but you can clone the repository and install the archetypes in your local maven repository. Just follow these steps:
```sh
git clone https://github.com/culturegraph/metafacture-archetypes.git
cd metafacture-archetypes
mvn clean install
cd ..
# Create a metafacture application:
mvn archetype:generate  -DarchetypeGroupId=org.culturegraph.archetypes -DarchetypeArtifactId=metafacture-application
# Maven should enter interactive mode and ask you for the name of your project etc.
# Once it has finished, you'll have a new maven project with a simply metafacture java example
# Create a metafacture plugin package:
mvn archetype:generate  -DarchetypeGroupId=org.culturegraph.archetypes -DarchetypeArtifactId=metafacture-plugin
# Maven should enter interactive mode and ask you for the name of your project etc.
# Once it has finished, you'll have a new maven project which can be compiled as a metafacture plugin. The plugin package can then be copied into the plugin folder of the metafacture-runner distribution to make the new command available in flux.
```

Please note that the metafacture versions in the archetypes are not up to date. You have to update the dependency in the poms of the generated projects to use the current metafacture-core version.

Best
Christoph

**Comment by cboehme** [comment]
This issue was moved to culturegraph/metafacture-core#269
