### ISSUE TITLE
Document installation

### ISSUE THREAD

**Issue by nichtich** [culturegraph/metafacture-runner#8]
The README.md should document installation as standalone application. Without being a Java developer. 

I found 
<https://github.com/culturegraph/metafacture-core/wiki/Flux-user-guide> and went so far, witout success:

~~~bash
$ wget https://github.com/culturegraph/metafacture-runner/archive/metafacture-runner-3.1.2.tar.gz
$ tar xzf metafacture-runner-3.1.2.tar.gz
$ cd metafacture-runner-metafacture-runner-3.1.2
$ ./src/main/scripts/flux.sh
./src/main/scripts/flux.sh: Zeile 51: $METAFACTURE_HOME/${project.build.finalName}.jar: Falsche Variablenersetzung.
cat: /home/voj/proj/flux/metafacture-runner-metafacture-runner-3.1.2/src/main/scripts/config/java-options.conf: Datei oder Verzeichnis nicht gefunden
Error: Unable to access jarfile
~~~

**Comment by cboehme** [comment]
Thanks for your hint. I have updated the readme file and added a short quickstart guide. For more details about why you couldn't run the example, please have a look at my comment [here](https://github.com/culturegraph/metafacture-runner/issues/6#issuecomment-113546697).

Cheers,
Christoph
